---

version: '3'

services:
    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter
        hostname: "1hostname1"
        restart: always
        network_mode: "bridge"
        ports:
            - "7100:9100"
    cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
        hostname: "1hostname1"
        restart: always
        network_mode: "bridge"
        ports:
            - "7200:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
